### ISSUE TITLE
Wrong final block length

### ISSUE THREAD

**Issue by GwilymNewton** [benkroeger/oniyi-ltpa#1]
Hi, we are seeing this error trying to use your lib.

We have run the exact same, token, key & passphrase though some a java lib, and it can decode it. So we are pretty sure our inputs are okay.

We have also but some console logs in to check you are reading all the data in okay.

It looks like there is an issue todo with `decipher.final();` in your `crypto-untils.js`, based on some google-foo it looks like it MIGHT be an issue todo with encoding, I tried messing around in there and trying out some suggested fixes, but without much luck.

Can you help us? 

`Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (crypto.js:181:26)
    at decrypt (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/utils/crypto-utils.js:21:21)
    at decryptLtpaToken2 (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/ltpa-utils.js:72:10)
    at getLtpaToken2Content (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/ltpa-utils.js:92:37)
    at Object.decode (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/ltpa2-factory.js:51:25)
    at ltpa2Factory (/Users/gwilymnewton/Box Sync/opentec/monkeying_about/ltpa_decrypt.js:19:35)
    at readKeyfile (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/ltpa2-factory.js:46:5)
    at properties.parse (/Users/gwilymnewton/Box Sync/opentec/node_modules/oniyi-ltpa/lib/ltpa-utils.js:45:5)
    at build (/Users/gwilymnewton/Box Sync/opentec/node_modules/properties/lib/read.js:397:17)
    at /Users/gwilymnewton/Box Sync/opentec/node_modules/properties/lib/read.js:474:5`

**Comment by GwilymNewton** [comment]
Our test code

`const moment = require('moment');
const { ltpa2Factory } = require('oniyi-ltpa');
 
const myLtpaToken2 = "<**REDACTED**>";

const LTPA_PASSWORD = '<**REDACTED**>'

const key = 'key.properties';
 
ltpa2Factory(key,LTPA_PASSWORD , (err, ltpa2) => {
 
  // Decode an existing token
  const ltpaToken2Content = ltpa2.decode(myLtpaToken2);
  console.log(ltpaToken2Content);
 
});`

**Comment by GwilymNewton** [comment]
Our key.properties file
```
com.ibm.websphere.ltpa.version=1.0
com.ibm.websphere.CreationDate=Mon Feb 02 12\:24\:13 GMT 2015
com.ibm.websphere.CreationHost=localhost
com.ibm.websphere.ltpa.3DESKey=<**REDACTED**>
com.ibm.websphere.ltpa.PrivateKey=<**REDACTED**>
com.ibm.websphere.ltpa.Realm=ApplicationCenter
com.ibm.websphere.ltpa.PublicKey=<**REDACTED**>
```

**Comment by benkroeger** [comment]
so, just to be sure that reading your `key.properties` correctly... can you try this

```javascript
ltpa2Factory('keys.properties', LTPA_PASSWORD, (err, ltpa2) => {
    console.log(ltpa2.getKeyfile());
});
```

that should provide you with all the private / public keys, including PEM format

**Comment by GwilymNewton** [comment]
Reading it in for sure:

```
Gwilyms-MacBook-Pro:monkeying_about gwilymnewton$ node ltpa_decrypt.js
Get key file { version: 1,
  creationDate: 'Mon Feb 02 12:24:13 GMT 2015',
  creationHost: 'localhost',
  realm: 'ApplicationCenter',
  publicKey: '...',
  des3Key: '...',
  privateKey: '...',
  privateKeyPEM: '...' }
```
Replaced the senstive bits with '...'

**Comment by benkroeger** [comment]
hm, I've just revalidated with my test ltpa keys and a live-created LtpaToken2. Are you trying to decrypt an LtpaToken2 or LtpaToken?

**Comment by GwilymNewton** [comment]
We are pretty sure its a LtpaToken2, its being issued by IBM ISAM

If it run it though
https://github.com/cosmin/samples/blob/master/LTPAUtils/LtpaUtils.java

We can decode it.

**Comment by GwilymNewton** [comment]
@benkroeger I just emailed our test data / keys over to you so you can try yourself

**Comment by benkroeger** [comment]
unfortunately the data / keys you sent are incomplete. It's missing at least the private key from `keys.properties`.
Also, the Java code you [sent as reference](https://github.com/cosmin/samples/blob/master/LTPAUtils/LtpaUtils.java#L96) uses `DESede/ECB/PKCS5Padding` which imho is a clear indicator for LtpaToken (not LtpaToken2).

[I have implemented `decoding` of LtpaToken](https://github.com/benkroeger/oniyi-ltpa/blob/master/lib/ltpa-utils.js#L76) in this module as well but didn't make it publicly available yet... since the `encode` part is not done yet.
Feel free to give it a try as well. (Although I only get a different error when trying to decode a LtpaToken value)

**Comment by benkroeger** [comment]
does that mean with [this](https://github.com/benkroeger/oniyi-ltpa/blob/e17ed2d4fa5043a7e64295e7f5c566a8afd5d246/lib/ltpa-utils.js#L76) it works for you? If yes, I can provide a simple update exposing an additional method (like `decodeV1` or so...)

**Comment by GwilymNewton** [comment]
Yes, it worked perfectly !

**Comment by GwilymNewton** [comment]
Thanks 👍
